### ISSUE TITLE
Segmentation fault error with Hoomd-blue examples 

### ISSUE THREAD

**Issue by angelaabongwa** [SSAGESLabs/PySAGES#189]
I believe there's a backend issue with either the extension module or the python interpreter. When I run any example in hoomd-blue, I get an error: Segmentation fault (core dumped)

**Comment by pabloferz** [comment]
Thanks for the bug report Angela. Does this happen at the end of the run or in the middle of the simulation? If it happens at the end, are you getting the results of the simulation?

I suspect this might have been introduced on some of the most recent changes in the hoomd-dlext repo.

**Comment by angelaabongwa** [comment]
It happens at the end and the output files (energy, histogram) are the updated accordingly.

**Comment by InnocentBug** [comment]
So your simulations finish correctly and only at the very end you experience a crash from the python interpreter?

Do you happen to run examples with MPI support?

**Comment by InnocentBug** [comment]
There are known issues with segfault with hoomd-blue.

-  If you initialize `hoomd.context.initialize()` inside an existing context, segfaults are expected.
   Do not do this in your `generate_context` function.
   ```python
   context = hoomd.context.SimulationContext()
   with context:
      hoomd.context.initialize()
      ...
   ```
   Instead do this:
   ```
   hoomd.context.initialize()
   context = hoomd.context.SimulationContext()
   with context:
      ...
   ```
-  At the end of simulations, XLA might try to release resources that are already released before.
   This is a known issue. We are working on a solution, but it is not priority right now, since all simulations are correctly executed.
   
The reported issue seems to be the latter, so I am going to close the issue for now.
